# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
# SPDX-License-Identifier: Apache-2.0

version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.10
    command:
      - /usr/local/bin/etcd
      - --name=etcd0
      - --data-dir=/etcd-data
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-advertise-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd0=http://0.0.0.0:2380
      - --initial-cluster-token=etcd-cluster-1
      - --initial-cluster-state=new
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd-data:/etcd-data
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 10s
      timeout: 5s
      retries: 5

  settingsservice:
    build:
      context: ../../../  # Build from project root
      dockerfile: src/server/settingsservice/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=settingsservice=info,warn
    command:
      - settingsservice
      - --etcd-endpoints=etcd:2379
      - --bind-address=0.0.0.0
      - --bind-port=8080
      - --log-level=info
    depends_on:
      etcd:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/system/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  etcd-data: