# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
#
# SPDX-License-Identifier: Apache-2.0

# DO NOT USE this file if you can see this comment.

apiVersion: v1
kind: Pod
metadata:
  name: piccolo-server
spec:
  hostNetwork: true
  hostPid: true
  containers:
  - name: etcd
    image: gcr.io/etcd-development/etcd:v3.5.24
    command: ["/usr/local/bin/etcd"]
    args: 
    - "--data-dir=/etcd-data"
    - "--listen-client-urls=http://127.0.0.1:2379,http://$(HOST_IP):2379"
    - "--advertise-client-urls=http://$(HOST_IP):2379"
    volumeMounts:
    - name: etcd-data
      mountPath: /etcd-data
  - name: apiserver
    image: ghcr.io/youngtaekiim/pullpiri:latest
    command: ["/piccolo/apiserver"]
    volumeMounts:
    - name: piccolo-yaml
      mountPath: /etc/piccolo/yaml
    - name: config-path
      mountPath: /etc/piccolo/settings.yaml
  - name: policymanager
    image: ghcr.io/youngtaekiim/pullpiri:latest
    command: ["/piccolo/policymanager"]
  - name: monitoringserver
    image: ghcr.io/youngtaekiim/pullpiri:latest
    command: ["/piccolo/monitoringserver"]
    volumeMounts:
    - name: piccolo-yaml
      mountPath: /etc/piccolo/yaml
    - name: config-path
      mountPath: /etc/piccolo/settings.yaml
  - name: settingsservice
    image: ghcr.io/youngtaekiim/pullpiri:latest
    command: ["/piccolo/settingsservice", "--bind-address=$(HOST_IP)", "--bind-port=8080", "--log-level=debug"]
    volumeMounts:
    - name: piccolo-yaml
      mountPath: /etc/piccolo/yaml
    - name: config-path
      mountPath: /etc/piccolo/settings.yaml
  volumes:
  - name: piccolo-yaml
    hostPath:
      path: /etc/piccolo/yaml
  - name: etcd-data
    hostPath:
      path: /etc/containers/systemd/piccolo/etcd-data
  - name: config-path
    hostPath:
      path: /etc/containers/systemd/piccolo/settings.yaml
