# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
#
# SPDX-License-Identifier: Apache-2.0

# DO NOT USE this file if you can see this comment.

apiVersion: v1
kind: Pod
metadata:
  name: piccolo-server
spec:
  hostNetwork: true
  hostPid: true
  containers:
  - name: apiserver
    image: localhost/pullpiri:latest
    command: ["/piccolo/apiserver"]
    volumeMounts:
    - name: piccolo-yaml
      mountPath: /etc/piccolo/yaml
    - name: config-path
      mountPath: /etc/piccolo/settings.yaml
    - name: shared-rocksdb
      mountPath: /tmp/pullpiri_shared_rocksdb
  - name: policymanager
    image: localhost/pullpiri:latest
    command: ["/piccolo/policymanager"]
    volumeMounts:
    - name: shared-rocksdb
      mountPath: /tmp/pullpiri_shared_rocksdb
  - name: monitoringserver
    image: localhost/pullpiri:latest
    command: ["/piccolo/monitoringserver"]
    volumeMounts:
    - name: shared-rocksdb
      mountPath: /tmp/pullpiri_shared_rocksdb
  - name: settingsservice
    image: localhost/pullpiri:latest
    command: ["/piccolo/settingsservice", "--bind-address=0.0.0.0", "--bind-port=8080", "--log-level=info"]
    volumeMounts:
    - name: piccolo-yaml
      mountPath: /etc/piccolo/yaml
    - name: config-path
      mountPath: /etc/piccolo/settings.yaml
    - name: shared-rocksdb
      mountPath: /tmp/pullpiri_shared_rocksdb
  volumes:
  - name: piccolo-yaml
    hostPath:
      path: /etc/piccolo/yaml
  - name: config-path
    hostPath:
      path: /etc/containers/systemd/piccolo/settings.yaml
  - name: shared-rocksdb
    hostPath:
      path: /tmp/pullpiri_shared_rocksdb
