# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
#
# SPDX-License-Identifier: Apache-2.0

# DO NOT USE this file if you can see this comment.

apiVersion: v1
kind: Pod
metadata:
  name: pullpiri-agent
spec:
  hostNetwork: true
  hostPid: true
  containers:
  - name: nodeagent
    image: localhost/pullpiri:latest
    command: ["/piccolo/nodeagent"]
    volumeMounts:
    - name: pullpiri-yaml
      mountPath: /etc/pullpiri/yaml
    - name: systemd
      mountPath: /etc/containers/systemd
  volumes:
  - name: pullpiri-yaml
    hostPath:
      path: /etc/pullpiri/yaml
  - name: systemd
    hostPath:
      path: /etc/containers/systemd
