[package]
name = "rocksdb-inspector"
version = "0.1.0"
edition = "2021"

[dependencies]
rocksdb = "0.22.0"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
clap = { version = "4.0", features = ["derive"] }