# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Scenario
metadata:
  name: bms
spec:
  condition:
    express: eq
    value: "BulkCharging"
    operands:
      type: DDS
      name: charging_status
      value: "/rt/piccolo/Charging_Status"
  action: update
  target: bms-algorithm-charging
