# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: antipinch-core
  annotations:
    io.piccolo.annotations.package-type: antipinch-v2.0
    io.piccolo.annotations.package-name: antipinch
    io.piccolo.annotations.package-network: default
  labels:
    app: antipinch-core
spec:
  hostNetwork: true
  containers:
    - name: antipinch
      image: sdv.lge.com/demo/antipinch-core:1.1
  terminationGracePeriodSeconds: 0
