# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
#
# SPDX-License-Identifier: Apache-2.0

[workspace]
resolver = "2"

members = [ 
    "actioncontroller",
    "filtergateway",
    "statemanager"
]

[workspace.dependencies]
common = { path = "../common" }
