apiVersion: v1
kind: Scenario
metadata:
  name: antipinch-disable
spec:
  condition:
  action: update
  target: antipinch-disable
---
apiVersion: v1
kind: Package
metadata:
  label: null
  name: antipinch-disable
spec:
  pattern:
    - type: plain
  models:
    - name: antipinch-disable-core
      node: HPC
      resources:
        volume: antipinch-volume
        network: antipinch-network
---
apiVersion: v1
kind: Volume
metadata:
  label: null
  name: antipinch-volume
spec: null
---
apiVersion: v1
kind: Network
metadata:
  label: null
  name: antipinch-netowrk
spec: null
---
apiVersion: v1
kind: Pod
metadata:
  name: antipinch-disable-core
  annotations:
    io.piccolo.annotations.package-type: antipinch-v1.0
    io.piccolo.annotations.package-name: antipinch
    io.piccolo.annotations.package-network: default
  labels:
    app: antipinch-core
spec:
  hostNetwork: true
  containers:
    - name: antipinch
      image: sdv.lge.com/demo/antipinch-core:1.0
  terminationGracePeriodSeconds: 0