apiVersion: v1
kind: Scenario
metadata:
  name: antipinch-enable
spec:
  condition:
  action: update
  target: antipinch-enable
---
apiVersion: v1
kind: Package
metadata:
  label: null
  name: antipinch-enable
spec:
  pattern:
    - type: plain
  models:
    - name: antipinch-enable-core
      node: HPC
      resources:
        volume: antipinch-volume
        network: antipinch-network
---
apiVersion: v1
kind: Volume
metadata:
  label: null
  name: antipinch-volume
spec: null
---
apiVersion: v1
kind: Network
metadata:
  label: null
  name: antipinch-netowrk
spec: null
---
apiVersion: v1
kind: Model
metadata:
  name: antipinch-enable-core
  annotations:
    io.piccolo.annotations.package-type: antipinch-v2.0
    io.piccolo.annotations.package-name: antipinch
    io.piccolo.annotations.package-network: default
  labels:
    app: antipinch-core
spec:
  hostNetwork: true
  containers:
    - name: antipinch
      image: sdv.lge.com/demo/antipinch-core:1.1
  terminationGracePeriodSeconds: 0