apiVersion: v1
kind: Scenario
metadata:
  name: helloworld
spec:
  condition:
   express: eq
   value: "true"
   operands:
     type: DDS
     name: value
     value: ADASObstacleDetectionIsWarning
  action: update
  target: helloworld
---
apiVersion: v1
kind: Package
metadata:
  label: null
  name: helloworld
spec:
  pattern:
    - type: plain
  models:
    - name: helloworld
      node: HPC
      resources:
        volume:
        network:
    - name: helloworld2
      node: ZONE
      resources:
        volume:
        network:
---
apiVersion: v1
kind: Model
metadata:
  name: helloworld
  annotations:
    io.piccolo.annotations.package-type: helloworld
    io.piccolo.annotations.package-name: helloworld
    io.piccolo.annotations.package-network: default
  labels:
    app: helloworld
spec:
  hostNetwork: true
  containers:
    - name: helloworld
      image: sdv.lge.com/bms/blis:1.0
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
---
apiVersion: v1
kind: Model
metadata:
  name: helloworld2
  annotations:
    io.piccolo.annotations.package-type: helloworld2
    io.piccolo.annotations.package-name: helloworld2
    io.piccolo.annotations.package-network: default
  labels:
    app: helloworld2
spec:
  hostNetwork: true
  containers:
    - name: helloworld2
      image: sdv.lge.com/bms/frism:1.0
  terminationGracePeriodSeconds: 0
  restartPolicy: Never