apiVersion: v1
kind: Scenario
metadata:
  name: timpani_test
spec:
  condition: null
  action: update
  target: timpani_test
---
apiVersion: v1
kind: Package
metadata:
  label: null
  name: timpani_test
spec:
  pattern:
    - type: plain
  models:
    - name: timpani_test
      node: HPC
      resources:
        volume:
        network:
---
apiVersion: v1
kind: Model
metadata:
  name: timpani_test
  annotations:
    io.piccolo.annotations.package-type: timpani_test
    io.piccolo.annotations.package-name: timpani_test
    io.piccolo.annotations.package-network: default
  labels:
    app: timpani_test
spec:
  hostNetwork: true
  containers:
    - name: timpani_test
      image: localhost/timpani_test:latest
      #command: ["./sample_apps", "-t", "-p", "50", "-d", "45", "-P", "70", "-a", "2", "-l", "5", "container_task"]
      command: ["./sample_apps", "-a", "2", "-l", "5", "container_task"]
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_NICE"]
      resources:
        limits:
          cpu: "3"
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
