[package]
name = "nodeagent"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { workspace = true }
tonic = "0.12.3"
tokio = { version = "1.36.0", features = ["full"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_yaml = "0.9"

