# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Pod
metadata:
  name: bms-frism
  annotations:
    io.piccolo.annotations.package-type: frism
    io.piccolo.annotations.package-name: bms
    io.piccolo.annotations.package-network: default
  labels:
    app: bms-frism
spec:
  hostNetwork: true
  containers:
    - name: frism
      image: localhost/frism:1.0
  terminationGracePeriodSeconds: 0
