# SPDX-License-Identifier: Apache-2.0

yaml_storage: /etc/piccolo/yaml
piccolo_cloud: http://172.31.26.216:41234
host:
  name: aws-ec2
  ip: 172.31.26.216
  type: vehicle
  role: master
dds:
  idl_path: src/vehicle/dds/idl
  domain_id: 100
  # Removed out_dir - will use Cargo's default OUT_DIR
