# SPDX-License-Identifier: Apache-2.0

yaml_storage: /etc/piccolo
piccolo_cloud: http://0.0.0.0:41234
host:
  name: HPC
  ip: 0.0.0.0
guest:
#  - name: ZONE
#    ip: 192.168.0.1

dds:
  idl_path: src/vehicle/dds/idl
  domain_id: 100
  out_dir: out