# SPDX-License-Identifier: Apache-2.0

yaml_storage: /etc/pullpiri/yaml
pullpiri_cloud: http://0.0.0.0:41234
host:
  name: HPC
  ip: 0.0.0.0
  type: vehicle
  role: master
dds:
  idl_path: src/vehicle/dds/idl
  domain_id: 100
  # Removed out_dir - will use Cargo's default OUT_DIR
