# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Package
metadata:
  label: null
  name: antipinch-enable
spec:
  pattern:
    - type: plain
  models:
    - name: antipinch-core
      node: HPC
      resources:
        volume: antipinch-volume
        network: antipinch-network
