# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api = { path = "../api" }
const_format = "0.2.33"
config = "0.14.1"
etcd-client = "0.14.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_yaml = "0.9"