name: Build and Push Container Image
on:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Container image for AMD64
      uses: docker/build-push-action@v4
      with:
        context: .
        file: containers/Dockerfile
        push: true
        platforms: linux/amd64
        tags: ghcr.io/${{ github.repository }}/pullpiri:${{ github.ref_name }}

    - name: Build and push Container image for ARM64
      uses: docker/build-push-action@v4
      with:
        context: .
        file: containers/Dockerfile-arm
        push: true
        platforms: linux/arm64
        tags: ghcr.io/${{ github.repository }}/pullpiri:${{ github.ref_name }}
