name: License Report Generator

# This workflow is designed to be reusable from other workflows
on:
  workflow_call:

jobs:
  license_report:
    name: Generate License Reports
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository with all submodules
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Set up the Rust toolchain (stable version)
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      # Enable caching of Rust dependencies to speed up builds
      - uses: Swatinem/rust-cache@v2

      # Install `cargo-about` tool used for license reporting
      - name: Install cargo-about
        run: cargo install cargo-about

      # Run your custom shell script to generate HTML license reports
      - name: Run license check script
        run: ./scripts/license_check.sh

      # Upload all generated license report files to GitHub Actions as artifacts
      - name: Upload license reports
        uses: actions/upload-artifact@v4
        with:
          name: license-report
          path: dist/licenses/*